name = "hono-rest-api-worker"
compatibility_date = "2024-08-08"
node_compat = true
account_id = ""

[placement]
mode = "smart"

[vars]
mySecretKey="secreet!"

[[d1_databases]]
binding = "DB"
database_name = "{database_name}"
database_id = "{database_id}"